# Code generated by PyGo transpiler. DO NOT EDIT.
from __future__ import annotations
from datetime import datetime
from decimal import Decimal
import enum

# Handlers register into the shared HANDLERS dict owned by the runtime client,
# so the pyclient serve loop can dispatch to them over the socket.
from core.runtime.pyclient import HANDLERS

class Empresa:
    """Generated ORM model from `model Empresa` (native sqlite3)."""

    id: str | None
    rfc: str
    razon_social: str
    nombre_comercial: str | None
    email: str | None
    telefono: str | None
    direccion: str | None
    ciudad: str | None
    estado: str | None
    codigo_postal: str | None
    pais: str = "MX"
    moneda: str = "MXN"
    activo: Boolean = true
    created_at: datetime | None
    updated_at: datetime | None

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.rfc = kwargs.get("rfc")
        self.razon_social = kwargs.get("razon_social")
        self.nombre_comercial = kwargs.get("nombre_comercial")
        self.email = kwargs.get("email")
        self.telefono = kwargs.get("telefono")
        self.direccion = kwargs.get("direccion")
        self.ciudad = kwargs.get("ciudad")
        self.estado = kwargs.get("estado")
        self.codigo_postal = kwargs.get("codigo_postal")
        self.pais = kwargs.get("pais")
        self.moneda = kwargs.get("moneda")
        self.activo = kwargs.get("activo")
        self.created_at = kwargs.get("created_at")
        self.updated_at = kwargs.get("updated_at")

    _table = "empresa"
    _columns = {"id": "TEXT", "rfc": "TEXT", "razon_social": "TEXT", "nombre_comercial": "TEXT", "email": "TEXT", "telefono": "TEXT", "direccion": "TEXT", "ciudad": "TEXT", "estado": "TEXT", "codigo_postal": "TEXT", "pais": "TEXT", "moneda": "TEXT", "activo": "TEXT", "created_at": "TEXT", "updated_at": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Usuario:
    """Generated ORM model from `model Usuario` (native sqlite3)."""

    id: str | None
    nombre: str
    email: str
    password_hash: str
    rol: str = usuario
    empresa: str
    created_at: datetime | None

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.nombre = kwargs.get("nombre")
        self.email = kwargs.get("email")
        self.password_hash = kwargs.get("password_hash")
        self.rol = kwargs.get("rol")
        self.empresa = kwargs.get("empresa")
        self.created_at = kwargs.get("created_at")

    _table = "usuario"
    _columns = {"id": "TEXT", "nombre": "TEXT", "email": "TEXT", "password_hash": "TEXT", "rol": "TEXT", "empresa": "TEXT", "created_at": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Producto:
    """Generated ORM model from `model Producto` (native sqlite3)."""

    id: str | None
    codigo: str
    nombre: str
    descripcion: str | None
    tipo: str = producto
    categoria: str | None
    unidad_medida: str = "pz"
    precio_unitario: Decimal = 0.00
    costo: Decimal | None
    stock_minimo: Decimal = 0
    empresa: str
    activo: Boolean = true
    created_at: datetime | None

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.codigo = kwargs.get("codigo")
        self.nombre = kwargs.get("nombre")
        self.descripcion = kwargs.get("descripcion")
        self.tipo = kwargs.get("tipo")
        self.categoria = kwargs.get("categoria")
        self.unidad_medida = kwargs.get("unidad_medida")
        self.precio_unitario = kwargs.get("precio_unitario")
        self.costo = kwargs.get("costo")
        self.stock_minimo = kwargs.get("stock_minimo")
        self.empresa = kwargs.get("empresa")
        self.activo = kwargs.get("activo")
        self.created_at = kwargs.get("created_at")

    _table = "producto"
    _columns = {"id": "TEXT", "codigo": "TEXT", "nombre": "TEXT", "descripcion": "TEXT", "tipo": "TEXT", "categoria": "TEXT", "unidad_medida": "TEXT", "precio_unitario": "REAL", "costo": "REAL", "stock_minimo": "REAL", "empresa": "TEXT", "activo": "TEXT", "created_at": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Categoria:
    """Generated ORM model from `model Categoria` (native sqlite3)."""

    id: str | None
    nombre: str
    descripcion: str | None
    tipo: str = producto
    empresa: str | None

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.nombre = kwargs.get("nombre")
        self.descripcion = kwargs.get("descripcion")
        self.tipo = kwargs.get("tipo")
        self.empresa = kwargs.get("empresa")

    _table = "categoria"
    _columns = {"id": "TEXT", "nombre": "TEXT", "descripcion": "TEXT", "tipo": "TEXT", "empresa": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Cliente:
    """Generated ORM model from `model Cliente` (native sqlite3)."""

    id: str | None
    nombre: str
    rfc: str | None
    email: str | None
    telefono: str | None
    direccion: str | None
    empresa: str
    created_at: datetime | None

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.nombre = kwargs.get("nombre")
        self.rfc = kwargs.get("rfc")
        self.email = kwargs.get("email")
        self.telefono = kwargs.get("telefono")
        self.direccion = kwargs.get("direccion")
        self.empresa = kwargs.get("empresa")
        self.created_at = kwargs.get("created_at")

    _table = "cliente"
    _columns = {"id": "TEXT", "nombre": "TEXT", "rfc": "TEXT", "email": "TEXT", "telefono": "TEXT", "direccion": "TEXT", "empresa": "TEXT", "created_at": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Proveedor:
    """Generated ORM model from `model Proveedor` (native sqlite3)."""

    id: str | None
    nombre: str
    rfc: str | None
    email: str | None
    telefono: str | None
    empresa: str
    created_at: datetime | None

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.nombre = kwargs.get("nombre")
        self.rfc = kwargs.get("rfc")
        self.email = kwargs.get("email")
        self.telefono = kwargs.get("telefono")
        self.empresa = kwargs.get("empresa")
        self.created_at = kwargs.get("created_at")

    _table = "proveedor"
    _columns = {"id": "TEXT", "nombre": "TEXT", "rfc": "TEXT", "email": "TEXT", "telefono": "TEXT", "empresa": "TEXT", "created_at": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Factura:
    """Generated ORM model from `model Factura` (native sqlite3)."""

    id: str | None
    tipo: str = venta
    folio: str
    serie: str | None
    fecha: datetime | None
    subtotal: Decimal = 0
    iva: Decimal = 0
    total: Decimal = 0
    cliente: str | None
    proveedor: str | None
    estatus: str = borrador
    empresa: str
    created_at: datetime | None

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.tipo = kwargs.get("tipo")
        self.folio = kwargs.get("folio")
        self.serie = kwargs.get("serie")
        self.fecha = kwargs.get("fecha")
        self.subtotal = kwargs.get("subtotal")
        self.iva = kwargs.get("iva")
        self.total = kwargs.get("total")
        self.cliente = kwargs.get("cliente")
        self.proveedor = kwargs.get("proveedor")
        self.estatus = kwargs.get("estatus")
        self.empresa = kwargs.get("empresa")
        self.created_at = kwargs.get("created_at")

    _table = "factura"
    _columns = {"id": "TEXT", "tipo": "TEXT", "folio": "TEXT", "serie": "TEXT", "fecha": "TEXT", "subtotal": "REAL", "iva": "REAL", "total": "REAL", "cliente": "TEXT", "proveedor": "TEXT", "estatus": "TEXT", "empresa": "TEXT", "created_at": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Inventario:
    """Generated ORM model from `model Inventario` (native sqlite3)."""

    id: str | None
    producto: str
    almacen: str = "default"
    stock_actual: Decimal = 0
    stock_minimo: Decimal = 0
    ubicacion: str | None
    empresa: str

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.producto = kwargs.get("producto")
        self.almacen = kwargs.get("almacen")
        self.stock_actual = kwargs.get("stock_actual")
        self.stock_minimo = kwargs.get("stock_minimo")
        self.ubicacion = kwargs.get("ubicacion")
        self.empresa = kwargs.get("empresa")

    _table = "inventario"
    _columns = {"id": "TEXT", "producto": "TEXT", "almacen": "TEXT", "stock_actual": "REAL", "stock_minimo": "REAL", "ubicacion": "TEXT", "empresa": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Pedido:
    """Generated ORM model from `model Pedido` (native sqlite3)."""

    id: str | None
    tipo: str = pedido
    folio: str
    fecha: datetime | None
    cliente: str
    subtotal: Decimal = 0
    total: Decimal = 0
    estatus: str = borrador
    empresa: str

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.tipo = kwargs.get("tipo")
        self.folio = kwargs.get("folio")
        self.fecha = kwargs.get("fecha")
        self.cliente = kwargs.get("cliente")
        self.subtotal = kwargs.get("subtotal")
        self.total = kwargs.get("total")
        self.estatus = kwargs.get("estatus")
        self.empresa = kwargs.get("empresa")

    _table = "pedido"
    _columns = {"id": "TEXT", "tipo": "TEXT", "folio": "TEXT", "fecha": "TEXT", "cliente": "TEXT", "subtotal": "REAL", "total": "REAL", "estatus": "TEXT", "empresa": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Empleado:
    """Generated ORM model from `model Empleado` (native sqlite3)."""

    id: str | None
    nombre: str
    apellidos: str | None
    email: str | None
    departamento: str | None
    puesto: str | None
    salario: Decimal | None
    fecha_ingreso: Date | None
    empresa: str

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.nombre = kwargs.get("nombre")
        self.apellidos = kwargs.get("apellidos")
        self.email = kwargs.get("email")
        self.departamento = kwargs.get("departamento")
        self.puesto = kwargs.get("puesto")
        self.salario = kwargs.get("salario")
        self.fecha_ingreso = kwargs.get("fecha_ingreso")
        self.empresa = kwargs.get("empresa")

    _table = "empleado"
    _columns = {"id": "TEXT", "nombre": "TEXT", "apellidos": "TEXT", "email": "TEXT", "departamento": "TEXT", "puesto": "TEXT", "salario": "REAL", "fecha_ingreso": "TEXT", "empresa": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Proyecto:
    """Generated ORM model from `model Proyecto` (native sqlite3)."""

    id: str | None
    nombre: str
    descripcion: str | None
    cliente: str | None
    estatus: str = activo
    presupuesto: Decimal | None
    empresa: str

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.nombre = kwargs.get("nombre")
        self.descripcion = kwargs.get("descripcion")
        self.cliente = kwargs.get("cliente")
        self.estatus = kwargs.get("estatus")
        self.presupuesto = kwargs.get("presupuesto")
        self.empresa = kwargs.get("empresa")

    _table = "proyecto"
    _columns = {"id": "TEXT", "nombre": "TEXT", "descripcion": "TEXT", "cliente": "TEXT", "estatus": "TEXT", "presupuesto": "REAL", "empresa": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

class Tarea:
    """Generated ORM model from `model Tarea` (native sqlite3)."""

    id: str | None
    proyecto: str
    titulo: str
    descripcion: str | None
    estatus: str = pendiente
    prioridad: str = normal
    fecha_fin: Date | None

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.proyecto = kwargs.get("proyecto")
        self.titulo = kwargs.get("titulo")
        self.descripcion = kwargs.get("descripcion")
        self.estatus = kwargs.get("estatus")
        self.prioridad = kwargs.get("prioridad")
        self.fecha_fin = kwargs.get("fecha_fin")

    _table = "tarea"
    _columns = {"id": "TEXT", "proyecto": "TEXT", "titulo": "TEXT", "descripcion": "TEXT", "estatus": "TEXT", "prioridad": "TEXT", "fecha_fin": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

