// Code generated by PyGo transpiler. DO NOT EDIT.
package generated

import (
	"time"

	"pygo-framework/core/runtime"
)

// ensure time is referenced even if no model uses DateTime.
var _ = time.Now

// Empresa is generated from the `model Empresa` declaration.
type Empresa struct {
	Id *string `json:"id" msgpack:"id"`
	Rfc string `json:"rfc" msgpack:"rfc"`
	RazonSocial string `json:"razon_social" msgpack:"razon_social"`
	NombreComercial *string `json:"nombre_comercial" msgpack:"nombre_comercial"`
	Email *string `json:"email" msgpack:"email"`
	Telefono *string `json:"telefono" msgpack:"telefono"`
	Direccion *string `json:"direccion" msgpack:"direccion"`
	Ciudad *string `json:"ciudad" msgpack:"ciudad"`
	Estado *string `json:"estado" msgpack:"estado"`
	CodigoPostal *string `json:"codigo_postal" msgpack:"codigo_postal"`
	Pais string `json:"pais" msgpack:"pais"`
	Moneda string `json:"moneda" msgpack:"moneda"`
	Activo Boolean `json:"activo" msgpack:"activo"`
	CreatedAt *time.Time `json:"created_at" msgpack:"created_at"`
	UpdatedAt *time.Time `json:"updated_at" msgpack:"updated_at"`
}

// Usuario is generated from the `model Usuario` declaration.
type Usuario struct {
	Id *string `json:"id" msgpack:"id"`
	Nombre string `json:"nombre" msgpack:"nombre"`
	Email string `json:"email" msgpack:"email"`
	PasswordHash string `json:"password_hash" msgpack:"password_hash"`
	Rol string `json:"rol" msgpack:"rol"`
	Empresa string `json:"empresa" msgpack:"empresa"`
	CreatedAt *time.Time `json:"created_at" msgpack:"created_at"`
}

// Producto is generated from the `model Producto` declaration.
type Producto struct {
	Id *string `json:"id" msgpack:"id"`
	Codigo string `json:"codigo" msgpack:"codigo"`
	Nombre string `json:"nombre" msgpack:"nombre"`
	Descripcion *string `json:"descripcion" msgpack:"descripcion"`
	Tipo string `json:"tipo" msgpack:"tipo"`
	Categoria *string `json:"categoria" msgpack:"categoria"`
	UnidadMedida string `json:"unidad_medida" msgpack:"unidad_medida"`
	PrecioUnitario string `json:"precio_unitario" msgpack:"precio_unitario"`
	Costo *string `json:"costo" msgpack:"costo"`
	StockMinimo string `json:"stock_minimo" msgpack:"stock_minimo"`
	Empresa string `json:"empresa" msgpack:"empresa"`
	Activo Boolean `json:"activo" msgpack:"activo"`
	CreatedAt *time.Time `json:"created_at" msgpack:"created_at"`
}

// Categoria is generated from the `model Categoria` declaration.
type Categoria struct {
	Id *string `json:"id" msgpack:"id"`
	Nombre string `json:"nombre" msgpack:"nombre"`
	Descripcion *string `json:"descripcion" msgpack:"descripcion"`
	Tipo string `json:"tipo" msgpack:"tipo"`
	Empresa *string `json:"empresa" msgpack:"empresa"`
}

// Cliente is generated from the `model Cliente` declaration.
type Cliente struct {
	Id *string `json:"id" msgpack:"id"`
	Nombre string `json:"nombre" msgpack:"nombre"`
	Rfc *string `json:"rfc" msgpack:"rfc"`
	Email *string `json:"email" msgpack:"email"`
	Telefono *string `json:"telefono" msgpack:"telefono"`
	Direccion *string `json:"direccion" msgpack:"direccion"`
	Empresa string `json:"empresa" msgpack:"empresa"`
	CreatedAt *time.Time `json:"created_at" msgpack:"created_at"`
}

// Proveedor is generated from the `model Proveedor` declaration.
type Proveedor struct {
	Id *string `json:"id" msgpack:"id"`
	Nombre string `json:"nombre" msgpack:"nombre"`
	Rfc *string `json:"rfc" msgpack:"rfc"`
	Email *string `json:"email" msgpack:"email"`
	Telefono *string `json:"telefono" msgpack:"telefono"`
	Empresa string `json:"empresa" msgpack:"empresa"`
	CreatedAt *time.Time `json:"created_at" msgpack:"created_at"`
}

// Factura is generated from the `model Factura` declaration.
type Factura struct {
	Id *string `json:"id" msgpack:"id"`
	Tipo string `json:"tipo" msgpack:"tipo"`
	Folio string `json:"folio" msgpack:"folio"`
	Serie *string `json:"serie" msgpack:"serie"`
	Fecha *time.Time `json:"fecha" msgpack:"fecha"`
	Subtotal string `json:"subtotal" msgpack:"subtotal"`
	Iva string `json:"iva" msgpack:"iva"`
	Total string `json:"total" msgpack:"total"`
	Cliente *string `json:"cliente" msgpack:"cliente"`
	Proveedor *string `json:"proveedor" msgpack:"proveedor"`
	Estatus string `json:"estatus" msgpack:"estatus"`
	Empresa string `json:"empresa" msgpack:"empresa"`
	CreatedAt *time.Time `json:"created_at" msgpack:"created_at"`
}

// Inventario is generated from the `model Inventario` declaration.
type Inventario struct {
	Id *string `json:"id" msgpack:"id"`
	Producto string `json:"producto" msgpack:"producto"`
	Almacen string `json:"almacen" msgpack:"almacen"`
	StockActual string `json:"stock_actual" msgpack:"stock_actual"`
	StockMinimo string `json:"stock_minimo" msgpack:"stock_minimo"`
	Ubicacion *string `json:"ubicacion" msgpack:"ubicacion"`
	Empresa string `json:"empresa" msgpack:"empresa"`
}

// Pedido is generated from the `model Pedido` declaration.
type Pedido struct {
	Id *string `json:"id" msgpack:"id"`
	Tipo string `json:"tipo" msgpack:"tipo"`
	Folio string `json:"folio" msgpack:"folio"`
	Fecha *time.Time `json:"fecha" msgpack:"fecha"`
	Cliente string `json:"cliente" msgpack:"cliente"`
	Subtotal string `json:"subtotal" msgpack:"subtotal"`
	Total string `json:"total" msgpack:"total"`
	Estatus string `json:"estatus" msgpack:"estatus"`
	Empresa string `json:"empresa" msgpack:"empresa"`
}

// Empleado is generated from the `model Empleado` declaration.
type Empleado struct {
	Id *string `json:"id" msgpack:"id"`
	Nombre string `json:"nombre" msgpack:"nombre"`
	Apellidos *string `json:"apellidos" msgpack:"apellidos"`
	Email *string `json:"email" msgpack:"email"`
	Departamento *string `json:"departamento" msgpack:"departamento"`
	Puesto *string `json:"puesto" msgpack:"puesto"`
	Salario *string `json:"salario" msgpack:"salario"`
	FechaIngreso *Date `json:"fecha_ingreso" msgpack:"fecha_ingreso"`
	Empresa string `json:"empresa" msgpack:"empresa"`
}

// Proyecto is generated from the `model Proyecto` declaration.
type Proyecto struct {
	Id *string `json:"id" msgpack:"id"`
	Nombre string `json:"nombre" msgpack:"nombre"`
	Descripcion *string `json:"descripcion" msgpack:"descripcion"`
	Cliente *string `json:"cliente" msgpack:"cliente"`
	Estatus string `json:"estatus" msgpack:"estatus"`
	Presupuesto *string `json:"presupuesto" msgpack:"presupuesto"`
	Empresa string `json:"empresa" msgpack:"empresa"`
}

// Tarea is generated from the `model Tarea` declaration.
type Tarea struct {
	Id *string `json:"id" msgpack:"id"`
	Proyecto string `json:"proyecto" msgpack:"proyecto"`
	Titulo string `json:"titulo" msgpack:"titulo"`
	Descripcion *string `json:"descripcion" msgpack:"descripcion"`
	Estatus string `json:"estatus" msgpack:"estatus"`
	Prioridad string `json:"prioridad" msgpack:"prioridad"`
	FechaFin *Date `json:"fecha_fin" msgpack:"fecha_fin"`
}

// RegisterRoutes wires the generated routes into a router.
// The router type is intentionally an interface stub for Fase 0; the
// supervisor/HTTP agent supplies the concrete router.
type Router interface {
	Handle(method, path string, h func(args map[string]interface{}) (interface{}, error))
}

func RegisterRoutes(r Router) {
}
