// Code generated by PyGo transpiler. DO NOT EDIT.
package generated

import (
	"time"

	"pygo-framework/core/runtime"
)

// ensure time is referenced even if no model uses DateTime.
var _ = time.Now

// Greeting is generated from the `model Greeting` declaration.
type Greeting struct {
	Id *string `json:"id" msgpack:"id"`
	Name string `json:"name" msgpack:"name"`
}

// Handler_hello delegates to the Python handler "hello" over the MessagePack socket.
func Handler_hello(args map[string]interface{}) (interface{}, error) {
	return runtime.CallPython(
		"hello",
		args,
	)
}

// RegisterRoutes wires the generated routes into a router.
// The router type is intentionally an interface stub for Fase 0; the
// supervisor/HTTP agent supplies the concrete router.
type Router interface {
	Handle(method, path string, h func(args map[string]interface{}) (interface{}, error))
}

func RegisterRoutes(r Router) {
	r.Handle("GET", "/hello/:name", func(args map[string]interface{}) (interface{}, error) {
		return Handler_hello(args)
	}, false, false)
}
