# Code generated by PyGo transpiler. DO NOT EDIT.
from __future__ import annotations
from datetime import datetime
from decimal import Decimal
import enum

# Handlers register into the shared HANDLERS dict owned by the runtime client,
# so the pyclient serve loop can dispatch to them over the socket.
from core.runtime.pyclient import HANDLERS

class Greeting:
    """Generated ORM model from `model Greeting` (native sqlite3)."""

    id: str | None
    name: str

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.name = kwargs.get("name")

    _table = "greeting"
    _columns = {"id": "TEXT", "name": "TEXT"}

    @classmethod
    def create(cls, **fields):
        """Insert a row and return the model instance."""
        from core.runtime.db import connect, ensure_table
        cols = list(fields.keys())
        placeholders = ", ".join("?" for _ in cols)
        col_names = ", ".join(cols)
        conn = connect()
        ensure_table(conn, cls._table, [
            f"{name} {typ}" for name, typ in cls._columns.items()
        ])
        cur = conn.execute(
            f"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})",
            [fields[c] for c in cols],
        )
        conn.commit()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (cur.lastrowid,)
        ).fetchone()
        conn.close()
        return cls.row_to_model(row, cur.lastrowid)

    @classmethod
    def find(cls, id):
        """Look up a row by rowid and return the model instance."""
        from core.runtime.db import connect
        conn = connect()
        row = conn.execute(
            f"SELECT * FROM {cls._table} WHERE rowid = ?", (id,)
        ).fetchone()
        conn.close()
        if row is None:
            return None
        return cls.row_to_model(row, id)

    @classmethod
    def row_to_model(cls, row, rowid=None):
        if row is None:
            return None
        data = {k: row[k] for k in cls._columns.keys()}
        if data.get("id") is None and rowid is not None:
            data["id"] = rowid
        return cls(**data)

def hello(name: str) -> Greeting:
    return Greeting(name=name)
HANDLERS["hello"] = hello

